CREATE DATABASE legacy_gym;
USE legacy_gym;

-- Members Table
CREATE TABLE MEMBERS (
    MEM_ID VARCHAR(15) PRIMARY KEY,
    PWD VARCHAR(100),
    GENDER ENUM('Male', 'Female', 'Other'),
    EMAIL VARCHAR(100) UNIQUE,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    PLAN_ID VARCHAR(15),
    CLASS_ID VARCHAR(15),
    BRANCH_ID VARCHAR(15),
    STATUS ENUM('Active', 'Inactive')
);

-- Owners Table
CREATE TABLE OWNERS (
    OWN_ID VARCHAR(15) PRIMARY KEY,
    PWD VARCHAR(100)
);

-- Plans Table
CREATE TABLE PLANS (
    PLAN_ID VARCHAR(15) PRIMARY KEY,
    PRICING DECIMAL(10, 2) NOT NULL,
    DURATION INT NOT NULL
);

-- Subscription Table
CREATE TABLE SUBSCRIPTION (
    PLAN_ID VARCHAR(15) NOT NULL,
    MEM_ID VARCHAR(15) NOT NULL,
    START_DATE DATE NOT NULL,
    PRIMARY KEY (PLAN_ID, MEM_ID),
    FOREIGN KEY (PLAN_ID) REFERENCES PLANS(PLAN_ID),
    FOREIGN KEY (MEM_ID) REFERENCES MEMBERS(MEM_ID)
);

-- Classes Table
CREATE TABLE CLASSES (
    CLASS_ID VARCHAR(15) PRIMARY KEY,
    CLASS_NAME VARCHAR(20),
    TRAINER_ID VARCHAR(15),
    DAY CHAR(3)
);

-- Trainers Table
CREATE TABLE TRAINERS (
    TRAIN_ID VARCHAR(15) PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    GENDER ENUM('Male', 'Female', 'Other'),
    EMAIL VARCHAR(100),
    BRANCH_ID VARCHAR(15)
);

-- Payments Table
CREATE TABLE PAYMENTS (
    TRANS_ID VARCHAR(15) PRIMARY KEY,
    SENDER_ID VARCHAR(15),
    RECEIVER_ID VARCHAR(15),
    AMOUNT DECIMAL(10, 2),
    TIMESTAMP DATETIME
);

-- Equipments Table
CREATE TABLE EQUIPMENTS (
    EQUIP_ID VARCHAR(15) PRIMARY KEY,
    BRANCH_ID VARCHAR(15),
    EQUIP_NAME VARCHAR(50),
    LAST_MAINTENANCE_DAY DATE,
    NEXT_MAINTENANCE_DAY DATE
);

-- Multivalued Phone Number Table for Members
CREATE TABLE MEM_PH (
    MEM_ID VARCHAR(15),
    PHONE_NUMBER VARCHAR(15),
    PRIMARY KEY (MEM_ID, PHONE_NUMBER),
    FOREIGN KEY (MEM_ID) REFERENCES MEMBERS(MEM_ID)
);

-- Multivalued Phone Number Table for Trainers
CREATE TABLE TRAIN_PH (
    TRAIN_ID VARCHAR(15),
    PHONE_NUMBER VARCHAR(15),
    PRIMARY KEY (TRAIN_ID, PHONE_NUMBER),
    FOREIGN KEY (TRAIN_ID) REFERENCES TRAINERS(TRAIN_ID)
);
